<a href="https://colab.research.google.com/github/DanaeMartinez01/Metodos-Numericos-/blob/main/LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def lu_factorization(A):
    """
    Implementa la factorización LU de una matriz A según el algoritmo 6.4.

    Parámetros:
        A (numpy.ndarray): Matriz cuadrada de dimensión n x n.

    Retorna:
        L (numpy.ndarray): Matriz triangular inferior con diagonal de 1.
        U (numpy.ndarray): Matriz triangular superior.
    """
    n = A.shape[0]
    L = np.eye(n)  # Inicializamos L con la matriz identidad
    U = np.zeros_like(A, dtype=float)  # Inicializamos U como una matriz de ceros

    for i in range(n):
        # Paso 4: Seleccionar l_ii y u_ii
        suma1 = sum(L[i, k] * U[k, i] for k in range(i))
        U[i, i] = A[i, i] - suma1
        if U[i, i] == 0:
            raise ValueError("Factorización imposible, pivote nulo encontrado.")

        # Paso 5: Calcular elementos de U y L
        for j in range(i + 1, n):
            suma2 = sum(L[i, k] * U[k, j] for k in range(i))
            U[i, j] = A[i, j] - suma2

        for j in range(i + 1, n):
            suma3 = sum(L[j, k] * U[k, i] for k in range(i))
            L[j, i] = (A[j, i] - suma3) / U[i, i]

    return L, U

# Ejemplo 2: Matriz A
A = np.array([
    [1, 1, 0, 3],
    [2, 1, -1, 1],
    [3, -1, -1, 2],
    [-1, 2, 3, -1]
], dtype=float)

# Aplicamos la factorización LU
try:
    L, U = lu_factorization(A)
    print("Matriz L (triangular inferior):")
    print(L)
    print("\nMatriz U (triangular superior):")
    print(U)
except ValueError as e:
    print(e)

# Verificación: A debe ser igual a L @ U
print("\nVerificación (L @ U):")
print(np.dot(L, U))

Matriz L (triangular inferior):
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

Matriz U (triangular superior):
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]

Verificación (L @ U):
[[ 1.  1.  0.  3.]
 [ 2.  1. -1.  1.]
 [ 3. -1. -1.  2.]
 [-1.  2.  3. -1.]]
