<a href="https://colab.research.google.com/github/DanaeMartinez01/Metodos-Numericos-/blob/main/Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Introducción a NumPy

	•	¿Qué es NumPy?
NumPy es una biblioteca de Python que permite hacer cálculos matemáticos rápidos y eficientes, ya que está optimizada para trabajar con grandes volúmenes de datos y para realizar operaciones matemáticas avanzadas.
	•	¿Por qué es útil?
NumPy es mucho más rápido que las listas de Python para operaciones matemáticas, y permite realizar operaciones sobre múltiples elementos de un array a la vez.

•	Instalación
Si aún no tienes NumPy, instálalo ejecutando esta celda:

In [ ]:
!pip install numpy

2. Importar NumPy

	•	El primer paso en cualquier proyecto que use NumPy es importarlo:

In [ ]:
import numpy as np

3. Creación de Arrays

	•	Arrays: Estructuras de datos que permiten almacenar elementos del mismo tipo. NumPy trabaja principalmente con arrays, que son similares a las listas, pero mucho más rápidos.
	•	Crear un array 1D:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


Crear arrays multidimensionales:

In [ ]:
# Array 2D (matriz)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

# Array 3D
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


4. Funciones Básicas para Crear Arrays

	•	NumPy incluye funciones para crear arrays de ceros, unos, valores constantes, o números aleatorios:

In [ ]:
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
full = np.full((2, 3), 7)
eye = np.eye(3)  # Matriz identidad
random_arr = np.random.random((2, 2))

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Full:\n", full)
print("Matriz identidad:\n", eye)
print("Array aleatorio:\n", random_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full:
 [[7 7 7]
 [7 7 7]]
Matriz identidad:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array aleatorio:
 [[0.73840172 0.91805938]
 [0.83050715 0.4444673 ]]


5. Operaciones Básicas con Arrays

	•	Realiza operaciones matemáticas de manera rápida:

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

suma = arr1 + arr2
resta = arr1 - arr2
multiplicacion = arr1 * arr2
division = arr1 / arr2

print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)

Suma: [5 7 9]
Resta: [-3 -3 -3]
Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]


6. Funciones Matemáticas en NumPy

	•	Puedes aplicar funciones matemáticas como np.sum, np.mean, np.max, np.sqrt y np.power a arrays:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("Suma:", np.sum(arr))
print("Promedio:", np.mean(arr))
print("Máximo:", np.max(arr))
print("Raíz cuadrada:", np.sqrt(arr))
print("Potencia (elevando cada elemento al cuadrado):", np.power(arr, 2))

Suma: 15
Promedio: 3.0
Máximo: 5
Raíz cuadrada: [1.         1.41421356 1.73205081 2.         2.23606798]
Potencia (elevando cada elemento al cuadrado): [ 1  4  9 16 25]


7. Indexación y Slicing en Arrays

	•	La indexación y el slicing te permiten seleccionar partes específicas de un array:

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("Elemento en la posición 1:", arr[1])
print("Último elemento:", arr[-1])
print("Slicing (del índice 1 al 3):", arr[1:4])

Elemento en la posición 1: 20
Último elemento: 50
Slicing (del índice 1 al 3): [20 30 40]


8. Modificación de la Forma de un Array

	•	Puedes cambiar la forma de un array sin modificar sus datos:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr_reshaped = arr.reshape(2, 3)
print("Array original:", arr)
print("Array reshaped (2x3):\n", arr_reshaped)

Array original: [1 2 3 4 5 6]
Array reshaped (2x3):
 [[1 2 3]
 [4 5 6]]


9. Tabla de Potencias

	•	Para crear una tabla de potencias (similar a un triángulo) que muestre valores elevados a diferentes exponentes, podemos usar un array 2D:

In [ ]:
# Crear un array de base
base = np.arange(1, 6)  # Números del 1 al 5

# Generar la tabla de potencias usando un bucle o broadcasting
potencias = np.array([np.power(base, i) for i in range(1, 6)])

print("Tabla de potencias:\n", potencias)

Tabla de potencias:
 [[   1    2    3    4    5]
 [   1    4    9   16   25]
 [   1    8   27   64  125]
 [   1   16   81  256  625]
 [   1   32  243 1024 3125]]


•	En esta tabla, cada fila representa el valor base elevado a una potencia diferente (1, 2, 3, etc.).

10. Álgebra Lineal con NumPy

	•	Operaciones avanzadas como el producto punto (np.dot), transposición (np.transpose), y más:

In [ ]:
# Producto punto
a = np.array([1, 2])
b = np.array([3, 4])
print("Producto punto:", np.dot(a, b))

# Multiplicación de matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Multiplicación de matrices:\n", np.dot(A, B))

# Transposición
print("Transposición de A:\n", A.T)

Producto punto: 11
Multiplicación de matrices:
 [[19 22]
 [43 50]]
Transposición de A:
 [[1 3]
 [2 4]]


11. Filtrado de Arrays

	•	Seleccionar elementos que cumplen una condición:

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("Elementos mayores a 30:", arr[arr > 30])

Elementos mayores a 30: [40 50]


12. Conclusión

	•	NumPy es una herramienta poderosa para realizar operaciones matemáticas complejas en Python. Esta Notebook te ha enseñado a crear arrays, realizar operaciones matemáticas y manipular datos de manera eficiente.